// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrGRuVBc3bk0u1yUzWCwn5qlQRWT63esw',
    appId: '1:221776206121:web:e885aded57cbc6341e7f38',
    messagingSenderId: '221776206121',
    projectId: 'chef-buddy-74e28',
    authDomain: 'chef-buddy-74e28.firebaseapp.com',
    storageBucket: 'chef-buddy-74e28.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4mqiY89sDeAg2Av3m-8NpO3Q30OGjmG0',
    appId: '1:221776206121:android:5a863087c31b9f391e7f38',
    messagingSenderId: '221776206121',
    projectId: 'chef-buddy-74e28',
    storageBucket: 'chef-buddy-74e28.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWTYMpclhNKmXhjW5_DJ-oHh1xvvciFGo',
    appId: '1:221776206121:ios:9c5cd6194d0837211e7f38',
    messagingSenderId: '221776206121',
    projectId: 'chef-buddy-74e28',
    storageBucket: 'chef-buddy-74e28.appspot.com',
    iosClientId: '221776206121-fdolcgv7lmrvd44d7fanrpnsrcnnlc9h.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChat',
  );
}
